services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      INIT_MEMORY: 8G
      MAX_MEMORY: 13G
      VERSION: 1.20.4
    volumes:
      - mc-data:/data
      - ./downloads:/downloads
  mc-backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "1h"
      RCON_HOST: mc
      INITIAL_DELAY: 0
    volumes:
      - mc-data:/data:ro
      - ./mc-backups:/backups

volumes:
  mc-data: {}
